<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Futuristic Dinner Planning Studio | Supper Future Line</title><meta name="description" content="Practical dinner planning, menu pacing and hosting guidance from Supper Future Line."><script async src="https://www.googletagmanager.com/gtag/js?id=G-0LY0HY7L01"></script>
<script>window.dataLayer=window.dataLayer||[];function gtag(){dataLayer.push(arguments)}
gtag('consent','default',{analytics_storage:'denied',ad_storage:'denied',ad_user_data:'denied',ad_personalization:'denied',wait_for_update:500});
gtag('js',new Date());gtag('config','G-0LY0HY7L01');</script>
<link rel="stylesheet" href="assets/style.css"></head><body class="home-page"><header class="signal-head">
  <a class="signal-brand" href="index.php" aria-label="Supper Future Line home"><i></i><span>SUPPER<br>FUTURE<br>LINE</span></a>
  <div class="signal-clock"><small>NEXT SIGNAL</small><b>19:30 / LDN</b></div>
  <nav class="desk-nav" aria-label="Primary"><a href="supper-method.html">Method</a><a href="menu-register.html">Menu register</a><a href="future-journal.html">Journal</a><a href="contact.html">Contact</a></nav>
  <button class="signal-toggle" aria-expanded="false" aria-controls="signal-ribbon"><span>Menu</span><i></i></button>
</header>
<div class="signal-ribbon" id="signal-ribbon" aria-hidden="true">
  <div><small>TRANSMISSION / NAVIGATION</small><p>A planning studio for dinners paced by flavour, time and atmosphere.</p></div>
  <nav><a href="index.php"><b>00</b>Home signal</a><a href="supper-method.html"><b>01</b>Supper method</a><a href="menu-register.html"><b>02</b>Menu register</a><a href="future-journal.html"><b>03</b>Future journal</a><a href="contact.html"><b>04</b>Contact studio</a></nav>
</div><main><section class="signal-hero" id="signal-01">
  <div class="hero-copy"><p class="eyebrow">TRANSMISSION 001 / DINNER, RECOMPOSED</p><h1>The table is<br><em>still becoming.</em></h1><p class="lead">Supper Future Line turns menu contrast, preparation time and table atmosphere into one clear evening sequence. No theatrical promises—just useful systems for meals that move well.</p><div class="hero-actions"><a class="pulse-link" href="menu-register.html">Enter the menu register <b>↗</b></a><button class="sound-toggle" aria-pressed="false">Ambient pulse <i></i></button></div></div>
  <figure><img src="assets/images/hero.png" alt="Sculptural future supper table with appetising multi-course dishes"><figcaption><span>LIVE TABLE STUDY</span><b>19:30—22:15</b></figcaption></figure>
  <div class="hero-orbit" aria-hidden="true"><i></i><i></i><i></i><span>01</span></div>
</section>
<section class="course-transmission" id="signal-02"><div class="marquee"><span>BRIGHT / DEEP / CRISP / SOFT / HOT / COOL / BRIGHT / DEEP / CRISP / SOFT / HOT / COOL</span></div><div class="transmission-copy"><p class="eyebrow">COURSE TRANSMISSION</p><h2>A menu is a sequence,<br>not a pile of favourites.</h2><p>Build progression through appetite, contrast and workload. Every course should make the next one easier to understand—and practical to serve.</p></div><ol><li><b>01</b><span>Open</span><small>bright + alert</small></li><li><b>02</b><span>Gather</span><small>warm + generous</small></li><li><b>03</b><span>Settle</span><small>deep + complete</small></li><li><b>04</b><span>Release</span><small>small + clear</small></li></ol></section>
<section class="flavour-orbit" id="signal-03"><header><p class="eyebrow">FLAVOUR ORBIT / INTERACTIVE</p><h2>Choose the pull<br>of the evening.</h2><p>Select a centre of gravity. The orbit suggests a counterpoint and a practical check, not a fixed recipe.</p></header><div class="orbit-console"><div class="orbit-wheel"><button class="active" data-orbit="bright">Bright</button><button data-orbit="earth">Earth</button><button data-orbit="smoke">Smoke</button><button data-orbit="silk">Silk</button><button data-orbit="crunch">Crunch</button><i></i><div><small>PRIMARY PULL</small><strong data-orbit-title>BRIGHT</strong><b data-orbit-score>74</b></div></div><article><small>COUNTER SIGNAL</small><h3 data-orbit-counter>Warm depth + soft grain</h3><p data-orbit-copy>Use acidity early, then move toward rounder flavours so the menu develops instead of repeating one sharp note.</p><dl><div><dt>Watch</dt><dd data-orbit-watch>acid fatigue</dd></div><div><dt>Test</dt><dd data-orbit-test>taste after resting</dd></div></dl></article></div></section>
<section class="supper-timeline" id="signal-04"><div class="timeline-intro"><p class="eyebrow">SERVICE TIMECODE</p><h2>Pace the work<br>before the plates.</h2><p>Shift the guest arrival and see the preparation windows move. Keep final-minute jobs few, visible and realistic.</p><div class="time-buttons"><button class="active" data-time="early">18:30</button><button data-time="prime">19:30</button><button data-time="late">20:30</button></div></div><div class="timecode"><div><span data-time-one>15:00</span><b>CALM PREP</b><p data-time-copy-one>Make dressings, wash leaves and set serving pieces.</p></div><div><span data-time-two>17:20</span><b>HEAT WINDOW</b><p data-time-copy-two>Begin slow roasting and bring chilled elements into sequence.</p></div><div><span data-time-three>18:15</span><b>FINAL SIGNAL</b><p data-time-copy-three>Warm plates, finish herbs and clear the work surface.</p></div><i></i></div></section>
<section class="future-plating" id="signal-05"><figure><img src="assets/images/process.png" alt="Overhead supper preparation arranged in a radial timecode"><figcaption>PREP MATRIX / ONE SURFACE / MANY WINDOWS</figcaption></figure><div><p class="eyebrow">PLATING WITHOUT PANIC</p><h2>Design the handoff.</h2><p class="lead">A beautiful plate is only useful if it can leave the kitchen at the right temperature and with the host still present.</p><ul><li><span>01</span><b>Fix the base</b><small>stable component placed first</small></li><li><span>02</span><b>Hold the heat</b><small>hot element enters late</small></li><li><span>03</span><b>Wake the edge</b><small>fresh finish added once</small></li></ul><a class="pulse-link dark" href="supper-method.html">Read the supper method <b>↗</b></a></div></section>
<section class="table-spectrum" id="signal-06"><div><p class="eyebrow">TABLE LIGHT / INTERACTIVE</p><h2>Set atmosphere<br>without losing the food.</h2><p>Choose a light profile to preview its service effect. Guests should still read expressions, plates and glassware comfortably.</p></div><div class="spectrum-stage" data-spectrum="warm"><div class="table-shape"><i></i><i></i><i></i><i></i></div><span data-spectrum-label>WARM FOCUS / 42%</span></div><div class="spectrum-controls"><button class="active" data-light="warm">Warm focus</button><button data-light="pearl">Pearl clear</button><button data-light="coral">Coral hour</button><p data-light-copy>Soft directional warmth, with enough neutral fill to keep greens and sauces legible.</p></div></section>
<section class="hosting-protocol" id="signal-07"><header><p class="eyebrow">HOSTING PROTOCOL / 04 MOVES</p><h2>Keep the system quiet.</h2></header><div class="protocol-grid"><article><b>01</b><h3>Welcome first</h3><p>Give coats, drinks and seating an obvious place before final kitchen work.</p></article><article><b>02</b><h3>Share the shape</h3><p>Mention the broad menu, dietary changes and approximate course rhythm.</p></article><article><b>03</b><h3>Clear in waves</h3><p>Reset only what the next course needs; avoid turning the table into a workstation.</p></article><article><b>04</b><h3>Release the ending</h3><p>Let dessert or tea stretch without making departure feel scheduled.</p></article></div></section>
<section class="dispatch-grid" id="signal-08"><header><p class="eyebrow">FUTURE JOURNAL / ORIGINAL DISPATCHES</p><h2>Useful notes for<br>the next supper.</h2><a href="future-journal.html">Open all twelve ↗</a></header><div><a href="journal-01.html"><span>01 / PACE</span><h3>Planning a Dinner Menu Around Timing</h3><b>READ SIGNAL ↗</b></a><a href="journal-05.html"><span>05 / TABLE</span><h3>Setting a Table for Easy Conversation</h3><b>READ SIGNAL ↗</b></a><a href="journal-10.html"><span>10 / LIGHT</span><h3>Using Lighting to Shape a Dinner Setting</h3><b>READ SIGNAL ↗</b></a></div></section>
<section class="final-signal" id="signal-09"><div class="end-orbit"><span>09</span><i></i></div><div><p class="eyebrow">FINAL SIGNAL / KEEP THE EVENING HUMAN</p><h2>Plan the sequence.<br>Leave room for surprise.</h2><p class="lead">The best future-facing dinner is still generous, understandable and possible to cook.</p><a class="pulse-link light" href="contact.html">Contact the supper studio <b>↗</b></a></div></section></main><footer>
  <div><h3>Explore</h3><a href="supper-method.html">Supper Method</a><a href="menu-register.html">Menu Register</a><a href="future-journal.html">Future Journal</a></div>
  <div><h3>Contact</h3><p class="one-line">3638 Westbourne Grove, London, UK, W2 5SH, GB</p><a class="one-line" href="tel:+12125559857">+1 2125559857</a><a class="one-line" href="mailto:hello@supperfutureline.com">hello@supperfutureline.com</a></div>
  <div><h3>Policies</h3><a href="privacy.html">Privacy</a><a href="terms.html">Terms</a><a href="refund.html">Refund</a><a href="shipping.html">Shipping</a></div>
</footer><aside class="consent" role="dialog" aria-label="Analytics choice"><p>Optional analytics helps us improve this dinner-planning studio. Advertising storage stays off.</p><button data-consent="allow">Allow analytics</button><button data-consent="deny">Decline</button></aside><script src="assets/app.js"></script></body></html>